### ISSUE TITLE
Anchors excluding the interference one are squashed and duplicated

### ISSUE THREAD

**Issue by ryanckim** [IoSR-Surrey/source-separation-anchors#1]
Hi Dom,

It's tricky to describe but when I run the example.py code, the interference anchor sounds ok, but the others have double of the target distortion/musical noise signals halved in time and duplicated within the same length to the interference. So for example the interference plays at normal speed but on top of that the distorted target plays at 2x speed twice during the same timeframe. 

This is the warning message by the way:

> /vol/vssp/maruss/ryan/conda_envs/sisec-eval/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.

 > from ._conv import register_converters as _register_converters

I haven't been able to find out what's really happening so far. I wonder whether this is related somehow to float64 / float32 difference or something, but I'm confused because the interference anchor is fine. I'll keep looking but would you possibly have a look as well?

Thanks,
Ryan

**Comment by deeuu** [comment]
Hey,

Sorry I can't reproduce these issues, though 'm not 100% I follow.

Can you create a new virtual environment and install this package with
`pip install -r requirements.txt`
Then run `python example.py` and tell me the name of the generated audio files which you believe are erroneous.

Cheers

**Comment by ryanckim** [comment]
I've started from scratch as you mentioned with a new environment etc. (previously used the sisec-eval environment) and the example works fine. Thanks. But I had one error saying

`SyntaxError:
 Non-ASCII character '\xe2' in file /user/HS203/ck0009/maruss/source-separation-anchors/ssanchors/anchors.py on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
(/vol/vssp/maruss/ryan/conda_envs/sisec-eval-anchors) ck0009@ssh03:~/maruss/source-separation-anchors$ cat ssanchors/anchors.py`

and had to insert this one line at the beginning of `anchors.py`:

`# -*- coding: utf-8 -*-`

I haven't committed this change yet, but I'll branch out from this and work on the modification. Thanks again!

**Comment by deeuu** [comment]
Thanks for that, I really need to test the support on python 2.7 (this is a unicode support issue).
